package ar.edu.unlu.blackjack.Enumerado;

public enum Evento {
    CRUPIER_BLACKJACK_Y_EMPATE,
    PERDIO_JUGADOR,
    GANADOR_JUGADOR,
    EMPATO_JUGADOR,
    JUGADOR_APOSTO,
    SALDO_AGREGADO_EMPATE,
    DEVUELTO_POR_SEGURO,
    PUNTUACION_FINAL_CRUPIER,
    ADJUDICAR_GANANCIA,
    ADJUDICAR_GANANCIA_BJ,
    APUESTA_AMBAS_MANOS,
    CRUPIER_PIDE_CARTA,
    MOSTRAR_MANO_CRUPIER,
    MOSTRAR_MANO_JUGADOR,
    CICLO_PARTIDA,
    CRUPIER_SE_PASO,
    CRUPIER_SE_PLANTA,
    NOTIFICAR_TURNO_JUGADOR,
    JUGADOR_CONECTADO,
    ACTUALIZAR_SALA_ESPERA,
    TODOS_JUGADORES_LISTOS,
    JUGADOR_MARCO_LISTO,
    NOTIFICAR_TURNO_APUESTA,
    PARTIDA_FINALIZADA,
    CARTA_REPARTIDA_JUGADOR,
    JUGADOR_SE_PASO,
    JUGADOR_SE_PLANTO,
    JUGADOR_LLEGO_21,
    MOSTRAR_MANOS_DIVIDIDAS,
    CAMBIAR_A_MANO2,
    OFRECER_SEGURO,
    GANANCIA_SEGURO_PAGADA,

    // eventos para el sistema de votacion
    INICIAR_VOTACION_NUEVA_PARTIDA,
    ACTUALIZAR_VOTOS,
    VOTACION_COMPLETADA,
    NUEVA_PARTIDA_INICIADA,
    JUEGO_TERMINADO_TODOS_SALIERON


}
